name: 版权问题
description : 提交版权问题
labels: ["copyright"]
body:
  - type: dropdown
    attributes:
      label: 问题类型
      description: 请选择您遇到的问题类型
      options:
        - 我具有该作品的版权，并且希望将其撤回
        - 我在别处发现了这个作品，并且作者明确申明禁止转载
        - 我发现了该作品被他人非法转载
        - 作品中为著名我的姓名或来源
        - 其他
    validations:
      required: true
  - type: input
    attributes:
      label: 原文链接
    validations:
      required: true
  - type: input
    attributes:
      label: 侵权链接
    validations:
      required: true
  - type: textarea
    attributes:
      label: 其他信息
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: 提交声明
      options:
        - label: 我确认以上信息是真实有效的
          required: true
        - label: 我确认我已经阅读了作者的版权声明
          required: true
  - type: markdown
    attributes:
      value: "**非常感谢您为保护版权和尊重原创付出努力！**"
      
